### ISSUE TITLE
Assign button crash client

### ISSUE THREAD

**Issue by PixelmonPRO** [alejandrocoria/MapFrontiers#1]
Crash, when try click `Assign button` (i have banner in the other hand).
Crash report link: https://gist.github.com/PixelmonPRO/f6c95c5c32159dbeef957e1a0537c32e

**Comment by alejandrocoria** [comment]
Thanks for the report!

- Does it happen every time you try to assign that banner?
- Is it a vanilla Minecraft banner or does it have something of another mod?
- Does it crash if you remove Optifine?

**Comment by PixelmonPRO** [comment]
> Thanks for the report!
> 
> * Does it happen every time you try to assign that banner?
> * Is it a vanilla Minecraft banner or does it have something of another mod?
> * Does it crash if you remove Optifine?

Yes, every time. I tried to change the hand in which I held the banner, but still there is a crash.
The banner is vanilla, white.
At the moment I can not check without optifine. I can check in +-10 hours.
