### ISSUE TITLE
Name lost

### ISSUE THREAD

**Issue by OcrSu** [alejandrocoria/MapFrontiers#13]
My server delineates and names regions, but when there are no players, or when the server restarts, the region names are reset to the default
Java11
Server:Catserver-1.16.5
Modpack:LCW4.0
https://www.curseforge.com/minecraft/modpacks/lcw/files

**Comment by alejandrocoria** [comment]
I am not able to replicate the problem. I don't know much about servers, but if it works like the Minecraft client, version 1.16.5 uses Java 8, not 11.

Some questions:
1. Do you have OP permissions?
2. When you change the shape of a frontier do other players see those changes?
3. When you change the name of a frontier do other players see that change?
4. Frontiers names have non-ascii characters (letters from languages other than English)?

**Comment by OcrSu** [comment]
> I am not able to replicate the problem. I don't know much about servers, but if it works like the Minecraft client, version 1.16.5 uses Java 8, not 11.
> 
> Some questions:
> 
> 1. Do you have OP permissions?
> 2. When you change the shape of a frontier do other players see those changes?
> 3. When you change the name of a frontier do other players see that change?
> 4. Frontiers names have non-ascii characters (letters from languages other than English)?
I have the OP, Frontiers uses the English name
But because ModernUI can only use Java11, I can't test if it's a Java problem for now.

**Comment by alejandrocoria** [comment]
Can you please pass me the frontiers.dat file as soon as you change the two lines of the name and again after closing the server.

**Comment by OcrSu** [comment]
[frontiers.dat.txt](https://github.com/alejandrocoria/MapFrontiers/files/8600772/frontiers.dat.txt)


> Can you please pass me the frontiers.dat file as soon as you change the two lines of the name and again after closing the server.

**Comment by alejandrocoria** [comment]
Can you send me the file creating a new frontier, after renaming it and closing the Info window, but before disconnecting from the server?

_Sorry for the delay, Github never notified me of your message. I just saw it because I manually entered this issue._

**Comment by OcrSu** [comment]
> Can you send me the file creating a new frontier, after renaming it and closing the Info window, but before disconnecting from the server?
> 
> _Sorry for the delay, Github never notified me of your message. I just saw it because I manually entered this issue._
[frontiers.dat.zip](https://github.com/alejandrocoria/MapFrontiers/files/8648062/frontiers.dat.zip)
I have put together a file of all the step periods

**Comment by alejandrocoria** [comment]
> I have put together a file of all the step periods

That's great, I'll take a look at it.

**Comment by alejandrocoria** [comment]
Neither the name nor the modification date reaches the server. Are you sure it's just the name that's not working and not the color or vertices as well?

**Comment by alejandrocoria** [comment]
But in EditName2 the name of a frontier was modified, not the new one but the one with 6 vertices. Hmmm I don't understand what is going on.

**Comment by OcrSu** [comment]
> 但是在 EditName2 中，边界的名称被修改了，不是新的边界，而是具有 6 个顶点的边界。嗯，我不明白发生了什么。

In editname1, I changed the first line of the name to "Test"
The second line is "Test2"

In editname2, the boundary name has been reset to the default, at which point I change the first line to "What"

**Comment by OcrSu** [comment]
> But in EditName2 the name of a frontier was modified, not the new one but the one with 6 vertices. Hmmm I don't understand what is going on.

Maybe We can go to platforms like discord to exchange ideas, which will be easier.

**Comment by alejandrocoria** [comment]
That "What" did make it to the file, but the rest didn't. I don't understand how that can happen.

**Comment by OcrSu** [comment]
I'll try to send you a server that has this problem later, maybe that will make it easier for you to find the problem

**Comment by alejandrocoria** [comment]
If I prepare a version of the mod with some debug logging, could you test it and then send me the log file?

**Comment by OcrSu** [comment]
yes,,i can

**Comment by alejandrocoria** [comment]
Ok, I don't have time right now, but I'll do it tomorrow. Thank you!

**Comment by alejandrocoria** [comment]
Before I do anything, can you pass me the latest minecraft log? Client and server.

**Comment by alejandrocoria** [comment]
Good news! I found the bug, it will be fixed in the next release, probably tomorrow.

**Comment by OcrSu** [comment]
That's great, waiting for the next update!

**Comment by alejandrocoria** [comment]
Fixed in 2.1.3
