### ISSUE TITLE
Clicking doesn't seem to respond

### ISSUE THREAD

**Issue by joe-vettek** [alejandrocoria/MapFrontiers#15]
![image](https://user-images.githubusercontent.com/82761814/167915003-2993c843-eb77-432b-9f90-27e72c30a331.png)

**Comment by alejandrocoria** [comment]
Where are you clicking that doesn't work?

**Comment by joe-vettek** [comment]
I think I should probably close this question for now, I haven't been able to get in touch with the MC for a while, too busy.
Excuse me.
