### ISSUE TITLE
The "add a member in group" button seems to be behind the text bar

### ISSUE THREAD

**Issue by SUPERgamer02122005** [alejandrocoria/MapFrontiers#16]
![Capture d’écran (1)](https://user-images.githubusercontent.com/72099023/172641449-d3b8a0dd-8eaa-400c-9b6a-58902597103c.png)
I think the title said it.

**Comment by alejandrocoria** [comment]
It seems to me that the problem is the scaling of the Minecraft GUI. With 1080p and the scale at 4 or automatic, the mod does not fit. You have to use a smaller scale.

At the moment I have no way to support that scale because I need to display a lot of information on some screens.

**Comment by SUPERgamer02122005** [comment]
Ok thank you I just changed the GUI scale and the button appeared. But in a future version, could you please make the mod support the Auto or 4 ? Thank you.

**Comment by alejandrocoria** [comment]
I'll try. The screen with the list of frontiers and the one of frontier info has many things and Minecraft is not very flexible for that.

**Comment by SUPERgamer02122005** [comment]
Ok thank you for your work.
