### ISSUE TITLE
[1.18.2 Fabric] Crash when going into Journey Map Fullscreen map in Multiplayer

### ISSUE THREAD

**Issue by Doctor-Duck** [alejandrocoria/MapFrontiers#17]
As the title says, my client is crashing whenever I go into the Journey Map fullscreen on a multiplayer server. Both the client and server have the mod installed.

Crash report: https://crashy.net/ta4eSYN6ga1imBvYP7nx

**Comment by alejandrocoria** [comment]
Doesn't happen without MapFrontiers? In the stack trace there is no mention of the mod.

**Comment by Doctor-Duck** [comment]
Nope. Upon removing MapFrontiers, it no longer crashes. I thought maybe it was conflicting with Journey Map Integrations, but I tested it with just MapFrontiers and Journey Map and I was still getting the crash. So maybe its something to do with Journey Map?

**Comment by Doctor-Duck** [comment]
I should note, I tested it first by just removing MapFrontiers from the server, and it still crashed the client. Then removing MapFrontiers from the client stopped the client from crashing when going into the fullscreen map.

**Comment by alejandrocoria** [comment]
I see you are using Journeymap 5.8.5. The correct version for MapFrontier Fabric is Journeymap 5.9.0beta1-fabric. Can you try that version please?

**Comment by Doctor-Duck** [comment]
Updated to Journeymap 5.9.0beta1-fabric on both the client and server and I am still getting the crash.

Crash log: https://crashy.net/Nr4Y6HDw8FyYYXFInorV

**Comment by alejandrocoria** [comment]
Can you tell me what modpack are you using? to see if I can recreate the crash.

**Comment by Doctor-Duck** [comment]
It's my own custom modpack. I have a whitelist only server up, or you could create your own server. 

Link: https://www.curseforge.com/minecraft/modpacks/duck-pack-3-fabric-edition

**Comment by alejandrocoria** [comment]
Well... I was able to replicate the error without the modpack, it seems that it is the only version that I forgot to test in multiplayer and it has a bug. I'll investigate.

**Comment by alejandrocoria** [comment]
Fixed in 1.18.2-2.3.3-beta2-fabric.
Thanks for reporting the bug.
