### ISSUE TITLE
[Feature Request] Integration with FTB Chunks

### ISSUE THREAD

**Issue by mxmeeple** [alejandrocoria/MapFrontiers#21]
It would be nice to be able to claim FTB chunks through the frontier UI
Journeymap already shows the claimed chunks but does not (afaik) allow you to claim them with the UI
Since Frontiers is a great UI for this and the functionality overlaps a fair amount, would it even be possible to do so?

**Comment by alejandrocoria** [comment]
[JourneyMap Integration](https://www.curseforge.com/minecraft/mc-mods/journeymap-integration) already does that.

**Comment by mxmeeple** [comment]
I was not aware of this, thank you
