### ISSUE TITLE
[Feature Request] Disable frontier creation and UI for groups

### ISSUE THREAD

**Issue by DrAv0011** [alejandrocoria/MapFrontiers#22]
Allows administrators to make so specific groups cannot interact, edit, create... with frontiers, only see them in the map.
And hide the settings buttons to prevent issues.

**Comment by alejandrocoria** [comment]
That already exists for global frontiers.

**Comment by alejandrocoria** [comment]
Is there anything you want to see changed in the current system?

**Comment by DrAv0011** [comment]
I have not been able to test it at this moment for lack or time.
But ill check everything once I'm able and send and update.
Maybe you may close the issue for the moment.
