### ISSUE TITLE
Option to not show the name/owner/etc on minimap

### ISSUE THREAD

**Issue by IceflowRE** [alejandrocoria/MapFrontiers#23]
Could you add an option to not show the name, owner, etc. on the minimap?
I still would like to have it visible on the fullscreen map, also the small notficiation right next to the minimap is fine.
The problem is, if you have already some waypoints there the map gets really clustered.

**Comment by alejandrocoria** [comment]
It is a good idea. Others asked me to add an option to hide the frontier only on the minimap, so I'm going to add separate options for fullscreen and minimap.
Lately I didn't have time to work on the mod, but when I get back to it I'm going to implement it.

**Comment by alejandrocoria** [comment]
Added in 2.5.0-beta1.
