### ISSUE TITLE
Frontier settings not saving. / Crashing when deleting frontier

### ISSUE THREAD

**Issue by zarzwour** [alejandrocoria/MapFrontiers#25]
When I try to edit frontiers settings specifically the ones regarding minimap/world map rendering, they will save for a few minutes or until I leave render distance and then return. Once I return they will be what they were before I changed them. As well when I try to delete a frontier from the frontier info menu the game crashes, but if I delete it via the all frontiers menu its fine

Minecraft 1.19.2
Fabric 0.14.17-1.19.2
MapFrontiers-1.19.2-2.5.0-beta1-fabric
journeymap-1.19.2-5.9.4-fabric

**Comment by alejandrocoria** [comment]
I can't replicate either of those two problems. Does this happen on a server or in singleplayer? Can you please upload the minecraft log (latest.log) after the two things happen?

**Comment by zarzwour** [comment]
[latest.log](https://github.com/alejandrocoria/MapFrontiers/files/11129920/latest.log)
[crash-2023-04-01_11.31.50-client.txt](https://github.com/alejandrocoria/MapFrontiers/files/11129923/crash-2023-04-01_11.31.50-client.txt)
i disconnected after saving the no minimap setting and it was active when I rejoined. then I deleted it through the info screen and crashed. here are both logs

**Comment by alejandrocoria** [comment]
Fixed in 2.5.0-beta2.

If you don't see your personal local frontiers when entering the server, you will need to move the personal_frontiers.dat file from the /mapfrontier/ folder to the /journeymap/data/mp/"savegame"/mapfrontier/ folder.

Thank you very much for your report.

**Comment by zarzwour** [comment]
Thank you! And you're very welcome
