### ISSUE TITLE
Not working server-side

### ISSUE THREAD

**Issue by ryu0q** [alejandrocoria/MapFrontiers#26]
It just doesn't recognize the server's Map Frontiers, even though they are on the same version.

**Comment by ryu0q** [comment]
Version on client and the server are same. 1.20.1-2.6.0-beta.
Tested with multiple players.

**Comment by alejandrocoria** [comment]
Are they both fabric or forge?
Please upload the latest.log here. Also the server log if you have access to it.

**Comment by ryu0q** [comment]
the database had somehow corrupted.
deleting it solved the issue and it started working again
