### ISSUE TITLE
Button are not showing 

### ISSUE THREAD

**Issue by Banane480** [alejandrocoria/MapFrontiers#27]
https://i.imgur.com/4ghIGpw.jpg

**Comment by alejandrocoria** [comment]
Do you have the mod on the client? What version of Minecraft, MapFrontiers and JourneyMap do you have?
If you press F8 does the settings screen open? If so, look at the first option that allows you to show/hide the buttons.

**Comment by Banane480** [comment]
Here is the list of my Journey map version : 

journeymap-1.12.2-5.7.1.jar
MapFrontiers-1.12.2-1.5.1.jar

When I press F8 I have this : 

https://i.imgur.com/3034UMe.png

**Comment by alejandrocoria** [comment]
The old versions of the mod do not work like the new ones. You can see an explanation of how it is used in the spoiler section on [curseforge](https://www.curseforge.com/minecraft/mc-mods/mapfrontiers)

**Comment by Banane480** [comment]
i downloaded all last versions of the mods but i still don't have the buttons :/ Seems to be a problem with my modpack

https://www.curseforge.com/minecraft/mc-mods/mapfrontiers/files?version=1.12.2
https://www.curseforge.com/minecraft/mc-mods/journeymap/files?version=1.12.2

**Comment by alejandrocoria** [comment]
Only as of 2.0.0 the mod is fully integrated into the JourneyMap map screen. There is no such version for Minecraft 1.12.2 because JourneyMap does not have the necessary API in that very old version. If you want to play on 1.12.2 you have to use the old interface of the mod.

**Comment by Banane480** [comment]
Ohh crap.... How can i use it ?

**Comment by alejandrocoria** [comment]
As I said, on the curseforge page, in the spoiler section it shows the recipe of the book that you need to manage frontiers.
