### ISSUE TITLE
Cant make global frontiers on my server

### ISSUE THREAD

**Issue by BarxNosp** [alejandrocoria/MapFrontiers#28]
I cant make frontiers global on my aternos server

**Comment by alejandrocoria** [comment]
Do you have OP permissions or did an OP give you permission to create global frontiers?

**Comment by BarxNosp** [comment]
I am the op.

**Comment by alejandrocoria** [comment]
Which version are you using? Is the same version on the server?

**Comment by BarxNosp** [comment]
I use MapFrontiers-1.20.1-2.6.0beta2-fabric an the server is 1.20.1

**Comment by alejandrocoria** [comment]
But is the same version of Mapfrontiers on the server?

**Comment by BarxNosp** [comment]
Yes

**Comment by alejandrocoria** [comment]
Please upload the latest client and server logs here.

**Comment by BarxNosp** [comment]
How latest?

**Comment by BarxNosp** [comment]
![16896696952005156078662621980060](https://github.com/alejandrocoria/MapFrontiers/assets/139824413/d5d95eb6-aedf-41d1-b27d-e7a5d29ad8aa)
This is the problem, i can't click personal

**Comment by BarxNosp** [comment]
By the way this server log:
https://mclo.gs/hxtwesH

**Comment by alejandrocoria** [comment]
The problem is that the server uses forge and you are using fabric. I still couldn't make the mod compatible between different mod loaders.

**Comment by BarxNosp** [comment]
So i must change the server software to fabric?

**Comment by alejandrocoria** [comment]
Yes, or change your client to Forge

**Comment by BarxNosp** [comment]
it does not work😭😭

**Comment by alejandrocoria** [comment]
Please upload the latest client and server logs. Also, remember that you need to re-enter the server after you are assigned OP permissions for the mod to detect it.

**Comment by BarxNosp** [comment]
I tried everything but it still doesn't work.
Is there an in-game command I should enable?

**Comment by alejandrocoria** [comment]
No. If you don't have permissions or the mod on the client doesn't detect the mod on the server you won't be able to create global frontiers, see global frontiers, share personal frontiers or edit permissions in mod settings (F8 by default).

**Comment by BarxNosp** [comment]
With F8 i'm not able to click groups and Actions too

**Comment by alejandrocoria** [comment]
This means that you do not have OP permissions or another user who has permissions or had permissions took away your permissions to edit those tabs or there is some bug and the server mod does not communicate correctly with the client mod.

If it is the second option and you have permission to edit server files you can delete the /mapfrontiers/settings.dat file to reset the mod's permissions.

**Comment by BarxNosp** [comment]
I don't have mapfrontiers folder

**Comment by alejandrocoria** [comment]
I don't know how an Aternos server works, but if the mod can't create the folder then you will never be able to create global frontiers.
