### ISSUE TITLE
MapFrontiers menu does not appear on JourneyMap fullscreen map.

### ISSUE THREAD

**Issue by IlyasBarbae** [alejandrocoria/MapFrontiers#30]
I am playing multiplayer using the Essentials mod. We are running Minecraft 1.20.1 with Fabric 0.14.21 and MapFrontiers 2.6.0. I installed ModMenu to check the settings, but it says that the fullscreen map buttons are on even though I don't see them when I open up the fullscreen map. My hotkey is still F8 because nothing else is conflicting, but even when I change the hotkey, it still doesn't work with the new keybind. The log is included below.
[latest.log](https://github.com/alejandrocoria/MapFrontiers/files/12233235/latest.log)

**Comment by alejandrocoria** [comment]
I can't replicate it. Check if it works correctly only with MapFrontiers and its dependencies. If so, it may be an incompatibility with a mod. You can do a binary search to find it:

> The binary search is a way of finding a faulty thing among a lot of other things, without having to remove the things one-by-one.
> This is useful for finding a broken mod among hundreds of mods, without having to spend time testing the mods one-by-one.
> The procedure is simple:
>   1. Remove half of the existing things, and put them aside.
>   2. Run the program / game.
>   3. Does the issue still exist?
>     If YES: Repeat from step 1 with the current things.
>     IF NO: Swap out the current things with the ones set aside, and repeat from step 1.
>   4. Repeat this process until the problematic thing/s have been found.
