### ISSUE TITLE
[1.20.1 forge] Problem with securejarhandler

### ISSUE THREAD

**Issue by Sgale952** [alejandrocoria/MapFrontiers#32]
```
To play on the server through the launcher, I need to apply a patch for securejarhandler.
After that, MapFrontiers refuses to run on both the server and the client.
At the same time, MapFrontiers worked perfectly with the modified securejarhandler on versions 1.18.2 and 1.19.2
```
* Java: Liberica Full JDK 17.0.8
* Minecraft: 1.20.1, Forge 47.1.0 (_also tested on Forge 47.1.43_)
* Mods: journeymap-1.20.1-5.9.12-forge.jar, MapFrontiers-1.20.1-2.6.0beta2-forge.jar
* Patch: [click](https://mirror.gravitlauncher.com/5.2.x/compat/patch/forge/securejarhandler.patch) (_I applied the patch manually. Maybe I made a mistake when build_)
* My securejarhandler: [securejarhandler.zip](https://github.com/alejandrocoria/MapFrontiers/files/12318012/securejarhandler.zip)
* Log on server: [click](https://pastebin.com/feY5D0ZY)
* Log on client: [click](https://pastebin.com/hJaz7Gdh)

**Comment by alejandrocoria** [comment]
I can't reproduce the problem, the patch doesn't seem to be responsible by looking at the code it modifies. There seems to be a problem with the jar in jar that MapFrontiers uses (to include the common-networking-forge mod).
I don't know anything about GravitLauncher or securejarhandler, but according to the [GravitLauncher wiki](https://gravitlauncher.com/clientbuild/) it doesn't support Forge for 1.20.1. Try Fabric.

**Comment by Sgale952** [comment]
The server uses the Arclight core, which allows you to use mods and plugins together. And also it is perfectly optimized (still sometimes there are bugs). So I can't switch to fabric.
I will ask the creator of common-networking for help. Thank you ❤️

**Comment by Sgale952** [comment]
Accidentally stumbled upon [this issue](https://github.com/EdwinMindcraft/origins-architectury/issues/232#issuecomment-1217962212).
Transferring files ```common-networking-forge-1.0.1-1.20.1.jar``` and ```metadata.json``` from ```MapFrontiers-1.20.1-2.6.0beta2-forge.jar\META-INF\jarjar\``` to ```mods``` helped me
