### ISSUE TITLE
[1.20.1 Forge] HUD not displayed

### ISSUE THREAD

**Issue by Sgale952** [alejandrocoria/MapFrontiers#33]
HUD (_name, author, banner near the minimap_) not displayed. I checked with default settings

* Version: 1.20.1, Forge 47.1.43 (_also Forge 47.1.39_)
* Java: Liberica Full JDK 17.0.8 (_also Oracle JDK 17.0.3_)
* Mods: journeymap-1.20.1-5.9.12, MapFrontiers-1.20.1-2.6.0

**Comment by alejandrocoria** [comment]
Does it show up in the HUD options?
Please upload the latest.log here.

**Comment by Sgale952** [comment]
Yes, HUD enabled and show up in options.
[Latest.log](https://pastebin.com/tLnEdeVH)

**Comment by alejandrocoria** [comment]
Fixed in 1.20.1-2.6.0beta3-forge.
Thank you!
