### ISSUE TITLE
[BUG] Frontier creation crashs

### ISSUE THREAD

**Issue by joaofranciscoguarda** [alejandrocoria/MapFrontiers#35]
I'm using a few mods and every other worked well, but mapFrontier latest version for 1.20.2 is crashing every time I try to do anything, I tried all panels and if I click in "done" or "create" the games closes and crashes. Don't have really usefull information from the crash. 

So I created a version to test with as minimum mods as possible, and got it again. Tried 5x different ways and everything just crash. Please, check if another players found the same bug. Thanks.

Mc version: 1.20.2
Modlist: Fabric, jorneymap, forgeconfigApiPort and mapFrontier.

**Comment by alejandrocoria** [comment]
~~Can you please upload the Minecraft log after the crash here? (latest.log)~~
Nevermind, I was able to reproduce it, I'll try to solve it.

**Comment by alejandrocoria** [comment]
Fixed in 1.20.2-2.6.0beta2. Thanks for letting me know!
