### ISSUE TITLE
Crash on 1.20.1 Fabric when creating a new Frontiers

### ISSUE THREAD

**Issue by ddfishel** [alejandrocoria/MapFrontiers#36]
In sorry for my English because I use Google Translate.
In general, I decided to install MapFrontiers on version 1.20.1 Fabric from the Modrinth website in my modpack. Everything works well until I start creating Frontiers. I click on "Create" and the crash begins.
This is not my modpack, I just thought that this might be a problem in some mods, but no.

- Minecraft 1.20.1
- Fabric loader 0.14.24
- fabric-api-0.90.7+1.20.1.jar
- ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
- journeymap-1.20.1-5.9.18-fabric.jar
- MapFrontiers-1.20.1-2.6.0-fabric.jar

Heres latest and crash log:
[crash-2023-11-25_00.26.52-client.txt](https://github.com/alejandrocoria/MapFrontiers/files/13462386/crash-2023-11-25_00.26.52-client.txt)
[latest.log](https://github.com/alejandrocoria/MapFrontiers/files/13462388/latest.log)

EDIT: I'll tested on the single and server, and crash begins.

**Comment by alejandrocoria** [comment]
Fixed in 1.20.1-2.6.0p1. Thanks for the report!
