### ISSUE TITLE
[Crash] Netwrok Direction Channel that Crash Client on Startup

### ISSUE THREAD

**Issue by Mini-kun** [alejandrocoria/MapFrontiers#37]
Mod version 2.6.0p1-forge
Mc version 1.20.1
Forge Version 47.1.3
Problem:

When ever a modpack(With the mod insite it) is close and relunched it Crash the Client whit a error for a Sided_setup event phase of 

"	Failure message: MapFrontiers (mapfrontiers) encountered an error during the sided_setup event phase
		java.lang.IllegalArgumentException: NetworkDirection Channel {mapfrontiers:packet_frontier} already registered"
		
Reprodoes:

1.open a minecraft instene with the mod
2.Open/Join any Singleplayer/server
3.Close down the Singleplayer/leave the server
4. Close down Minecraft
5. Reboot Minecraft
6. get the error near the end of the startup

**Comment by alejandrocoria** [comment]
I can't replicate it, can you drop the latest.log here and put a link to a modpack with which it happens?

**Comment by itsdeadfrosty** [comment]
> I can't replicate it, can you drop the latest.log here and put a link to a modpack with which it happens?

im also having this issue, i can do all that but my modpack is 600 mods T_T

i lied, my log mentions this mod but its actually the create: interiors mod... why does it mention this one then? so odd. maybe a conflict?

[crash-2024-02-25_15.02.42-fml.txt](https://github.com/alejandrocoria/MapFrontiers/files/14397684/crash-2024-02-25_15.02.42-fml.txt)
[latest.log](https://github.com/alejandrocoria/MapFrontiers/files/14397685/latest.log)

**Comment by alejandrocoria** [comment]
Can you please try removing Sinytra Connector, all Fabric mods and the Fabric API?
According to the log, the fabric mods it finds are:
SuperBetterGrass
End's Phantasm
Better Nether
Shield Overhaul
Better End
WunderLib
BCLib

**Comment by itsdeadfrosty** [comment]
after attempting to add
https://github.com/Fuzss/magnumtorch

it also crashed, saying map frontiers was the culprit

[latest.log](https://github.com/alejandrocoria/MapFrontiers/files/14397749/latest.log)
[crash-2024-02-25_15.32.43-fml.txt](https://github.com/alejandrocoria/MapFrontiers/files/14397750/crash-2024-02-25_15.32.43-fml.txt)

gonna try adding both mods and removing frontiers and see if anything changes

**Comment by itsdeadfrosty** [comment]
> Can you please try removing Sinytra Connector, all Fabric mods and the Fabric API? According to the log, the fabric mods it finds are: SuperBetterGrass End's Phantasm Better Nether Shield Overhaul Better End WunderLib BCLib

no.

connector allows me to add a  lot of fabric mods and it works great. id rather forgo map frontiers than do without connector and a handful of fabric mods

**Comment by alejandrocoria** [comment]
I understand, it is to know if the incompatibility is with that mod or not. That mod is in beta and must make internal changes to achieve what it does.

**Comment by itsdeadfrosty** [comment]
> I understand, it is to know if the incompatibility is with that mod or not. That mod is in beta and must make internal changes to achieve what it does.

gotcha. well if i uninstall connector its gonna lead to 90 other things crashing, so its not really practical for me to do that.

however i can offer this:

https://drive.google.com/file/d/1Z8GIWfKaUx0HExCmLOLxTTU4Lt3_DPXv/view?usp=drive_link

i figure youd be able to test it better than i could and with less waiting time inbetween

you dont have to, but im just gonna forgo the mod for now, and dont have a huge interest in tinkering for hours with it, especially cause im in college rn for CompSci and im swamped w schoolwork

but this modpack has a LOT of commonly used mods for you to check against and i wish you luck

**Comment by alejandrocoria** [comment]
I'll check it out when I have time. Sorry for the inconvenience and thank you for reporting it.

**Comment by itsdeadfrosty** [comment]
no prob, hope u get it figured out and i can come back to it one day

**Comment by alejandrocoria** [comment]
I think this problem is fixed in 2.6.0p3.
If not, you can let me know here.
