### ISSUE TITLE
[Crash] Crash when opening worlds in 1.20.4

### ISSUE THREAD

**Issue by Iautner** [alejandrocoria/MapFrontiers#38]
Everything seems to be working fine with the 1.20.2 version of MapFrontiers with what I have tested, but after saving a world in 1.20.4 and opening the world back up it crashes.
I hope this log can help.
[crash-2023-12-27_06.39.29-server.txt](https://github.com/alejandrocoria/MapFrontiers/files/13779335/crash-2023-12-27_06.39.29-server.txt)

**Comment by alejandrocoria** [comment]
The version for 1.20.2 does not work on 1.20.4.
I'm working on that version.
