### ISSUE TITLE
Frontier Book dosent appear

### ISSUE THREAD

**Issue by minho2011** [alejandrocoria/MapFrontiers#42]
why???

**Comment by alejandrocoria** [comment]
How to know.

Please tell me which versions of Minecraft and MapFrontiers you use, which mod loader, if it is singleplayer or multiplayer.

**Comment by minho2011** [comment]
minecraft 1.19.4
MapFrontiers 2.5.1

**Comment by alejandrocoria** [comment]
Only versions older than 2 have the book. For your version the mod is controlled from the JourneyMap fullscreen map. The buttons appear on the right.
