### ISSUE TITLE
Crash on Load

### ISSUE THREAD

**Issue by Phantasmal-Rin** [alejandrocoria/MapFrontiers#45]
Sometimes the mod causes a loading error where it says its already loaded and thus cant load now then crashed the game.
![image](https://github.com/alejandrocoria/MapFrontiers/assets/45186329/3e409a1e-c266-4381-b782-a87676d7a9f3)
This is being tested as part of a mod pack. It does not seem to many or few other mods i have loaded the issue persists.
Main complaint is that its not consistent. Sometime it break but next load its fine. Other times i crash 3+ times in a row. Makes testing for conflicts very hard.
.
Will try provide any additional information that can be useful upon request.
.
Minecraft: 1.20.1
Forge: 47.2.19
FTB Chunks: 2001.3.0
JourneyMap: 1.20.1-5.9.21-forge ( i tried newer version aswell)
JourneyMap Intergration: 1.20.1-0.14-45
Map Frontiers: Tried both. 2.6.0 and 2.6.0p1

**Comment by alejandrocoria** [comment]
Please try this version:
[MapFrontiers-1.20.1-2.6.0p1-forge.zip](https://github.com/user-attachments/files/15523441/MapFrontiers-1.20.1-2.6.0p1-forge.zip)


New requirements:
- Forge: 47.2.30
- JourneyMap: 5.9.22

If you encounter the problem again please drop the latest.log file here.

**Comment by alejandrocoria** [comment]
Did you have a chance to try it?

**Comment by Phantasmal-Rin** [comment]
Have not been able too yet. Will tonight. Tho may be hard to tell since it wasn't 100% of the time just random.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by alejandrocoria** [comment]
I understand, thank you!

**Comment by Phantasmal-Rin** [comment]
Hey. The issue seems to be fixed.
But since it only sometimes appears I won't be certain for a while.
Since I haven't gotten it in 10 tries, I assume what ya said worked. I'll let ya know if it reappears even.
Thanks a lot.

________________________________

**Comment by alejandrocoria** [comment]
I only updated the dependencies so I don't know what the bug was or why it was fixed. I'll wait a while before publishing it.

Thank you very much for your time and attention.

**Comment by alejandrocoria** [comment]
Released version 1.20.1-2.6.0p2 with the fix.
Thanks again.
