### ISSUE TITLE
(1.20.1-2.6.0p2)Frontiers don't save properly.

### ISSUE THREAD

**Issue by Hunter-495** [alejandrocoria/MapFrontiers#47]
Issue: In version the listed version (What I was using when I discovered the bug), frontiers that are created will not be saved, and if you exit and come back they will be missing.

Steps to reproduce: Join a world > Create a frontier > Exit > Rejoin > Frontier is missing, including from the menu.

NOTE: Issue is not present in 2.6.0p1, whatever fix was made to stop the crash on startup (Which I haven't experienced) created this issue.

I Initially thought this was a mod incompatibility, but realized it couldn't be, as no other mod (unless you count Journeymap itself), should even interact with this mod.

**Comment by alejandrocoria** [comment]
What mod loader and version are you using?

**Comment by Hunter-495** [comment]
Quilt 0.26.0.

**Comment by alejandrocoria** [comment]
Fixed in 2.6.0p3.
It was a problem in Common Networking. Thanks to Mysticdrew who solved it very quickly, I wasted most of the time trying to build the project on my PC due to problems with Gradle.

Thanks for your report and sorry for the inconvenience.
