### ISSUE TITLE
bannerDisplay ISSUE

### ISSUE THREAD

**Issue by salaka2** [alejandrocoria/MapFrontiers#49]
![image](https://github.com/alejandrocoria/MapFrontiers/assets/174796250/b89f1c1b-39ca-4e5f-a582-91ec04835658)
The game only crashes when I'm in some area that has a banner.

**Comment by alejandrocoria** [comment]
What version of the mod and mod loader?

**Comment by alejandrocoria** [comment]
Should be fixed in beta 2.
