### ISSUE TITLE
Is it required for MapFrontiers to use java 21?

### ISSUE THREAD

**Issue by tajemniktv** [alejandrocoria/MapFrontiers#50]
Hey, so I have my instance with lots of mods and to try to improve performance even more, I decided to go with a Java from Graal ([GraalVM](https://www.graalvm.org)) in version 22, although when trying to run the instance with MapFrontiers, it requires to use the 21 version. My question is to is this really required, and if so - why is that? I'm a bit aware that some things could break, but most mods work eitherway and I was wondering, whether that could be change to allow of the 22 java version usage... Unless that's not possible cuz of some things that got changed in code - that's understandable. But the question is mostly a curiosity thinglol 
Cheers:)

**Comment by alejandrocoria** [comment]
It is not a real requirement. The Java version change is something recent and I did not realize the possibility of allowing higher versions.

It is in Fabric that you are having the problem, right?

**Comment by tajemniktv** [comment]
Yeah, I'm using Fabric loader. 
Here's a full log from Prism, with the java version, specs mod list and hopefully everything you might need: https://mclo.gs/xD13Per

EDIT: Here's the log from trying to run with MapFrontiers: https://mclo.gs/sEBlweK
![image](https://github.com/alejandrocoria/MapFrontiers/assets/12156943/f5e7a475-8a8b-4d91-b975-f99ab08dbc96)

**Comment by alejandrocoria** [comment]
It will be solved in the next beta. Thanks for the report.

**Comment by alejandrocoria** [comment]
Fixed in beta 2.
Thanks again.
