### ISSUE TITLE
Frontiers disappeared

### ISSUE THREAD

**Issue by mawimmer** [alejandrocoria/MapFrontiers#54]
Yesterday out of nowhere almost all frontiers disappeared. I checked the files. They are still saved but ingame they are not available anymore...
[LogsnFiles.zip](https://github.com/user-attachments/files/16470340/LogsnFiles.zip)
happy to help resolve this, just let me know what you need
MC Version 1.20.1
MapFrontiers-1.20.1-2.6.0p1-forge
journeymap-1.20.1-5.9.18p1-forge

**Comment by mawimmer** [comment]
i actually restarted the server yesterday and it didnt fix anything, just did it again and now they are back...

**Comment by alejandrocoria** [comment]
You should update to the latest version: 1.20.1-2.6.0p4-forge
