### ISSUE TITLE
Crash when loading into a world when combined with Continuity

### ISSUE THREAD

**Issue by airxiti2** [alejandrocoria/MapFrontiers#55]
The game crashes when loading into a world / joining a server while Loading Terrain when combined with Continuity. 
[latest.log](https://github.com/user-attachments/files/16590059/latest.log)

**Comment by alejandrocoria** [comment]
I don't have access to my PC for a couple of days. I don't know that mod but I can't imagine why there would be an incompatibility.

Does the game work correctly removing only MapFrontiers? And removing only Continuity?

**Comment by airxiti2** [comment]
Okay, I have to apologize. It had nothing to do with MapFrontiers, just Continuity. I think I thought MapFrontiers had something to do with it because it started crashing when I installed it, but I also updated Fabric API at the same time which actually caused the crash. Sorry and Thanks :)

**Comment by alejandrocoria** [comment]
No problem!
