### ISSUE TITLE
BUG UI

### ISSUE THREAD

**Issue by salaka2** [alejandrocoria/MapFrontiers#59]
![image](https://github.com/user-attachments/assets/f3b7bb72-7394-4f54-b137-aa50a82b518e)
A problem with a large area that simply blocks the entire screen

**Comment by alejandrocoria** [comment]
Tell me what version of Minecraft, MapFrontiers, JourneyMap and modloader you are using.

**Comment by salaka2** [comment]
Minecraft 1.21.1
Fabric 0.16.4
fabric-api-0.103.0+1.21.1
journeymap-fabric-1.21-6.0.0-beta.23
MapFrontiers-1.21-2.6.0p2-fabric

**Comment by alejandrocoria** [comment]
It will be fixed in JourneyMap beta 25.
Thanks for letting us know.
