### ISSUE TITLE
Frontiers don't render on fullscreen map, only on the minimap.

### ISSUE THREAD

**Issue by Orvngex** [alejandrocoria/MapFrontiers#6]

**Comment by Orvngex** [comment]
Update to this: it will render if I switch the map mode.

**Comment by alejandrocoria** [comment]
Sorry, but there is nothing I can do about that. It's a bug in JourneyMap 1.12 that's been around for a long time.

**Comment by Orvngex** [comment]
All good, thank you!

**Comment by mysticdrew** [comment]
This issue is fixed in 5.7.2 of journeymap for 1.16.5. So when frontiers is released it will work better.
