### ISSUE TITLE
Game crash while launching

### ISSUE THREAD

**Issue by Rafii2198** [alejandrocoria/MapFrontiers#61]
I apologize for lack of information, I currently do not have much time to test this out and figure out what is the issue, but I am providing a crash report and I hope it contains needed information. https://mclo.gs/nXPoGpK
Playing on mc 1.21.1 neoforge 21.1.60, the game crashes and neoforge reports that this mod is the issue it is also mentioned in the report itself.

**Comment by alejandrocoria** [comment]
Please try the latest version of Forge Config API Port.

**Comment by Rafii2198** [comment]
Thanks that worked. And my apologies, I thought the launcher downloaded latest version it for some reason didn't, would it be possible to mark the mod to require specific Forge Config API Port version like it is possible on Fabric? I don't know much about Neoforge in that regard

**Comment by alejandrocoria** [comment]
No problem.
Yes, the mod asks for the version you had because that works fine in 1.21, it seems that it doesn't in 1.21.1.
