### ISSUE TITLE
Slight problem with my custom modpack (bugged?)

### ISSUE THREAD

**Issue by BatteryAc1dd** [alejandrocoria/MapFrontiers#62]
_Hello MapFrontiers devs! sliiiight problem._
So, I absolutely LOVE your map tool for JourneyMap, and was mid-making a teeny little modpack for me to build some cool things on. downloaded JourneyMap and Frontiers and came across an issue when loading. 
everything seems fine up until **joining** the worlds I make, and then it crashes and says the following;

> suspected mod [that crashed it]: Common Networking (commonnetworking), Version: 1.0.16-1.21
		at TRANSFORMER/commonnetworking@1.0.16-1.21/commonnetwork.networking.ForgeNetworkHandler.sendToServer(ForgeNetworkHandler.java:58)

So, this 'commonnetwork' thingo appears to be related solely to the Frontiers mod, as everything else comes back fine. I really don't want to have to use my modpack without this mod because it can be really handy for keeping track of my areas and claims, but it literally will not let me join my worlds without it turned off.
My version is 1.21.1, the latest version (as I only made this modpack today lol), and it's definetely not a RAM or PC based issue as I have allocated a decent (but not extreme) amount of RAM and my PC can typically run modpacks much larger in scale.
I understand the crashes could be a legit bug as the new versions are like - BRAND new, so I totally get if this is a bug!
for now I'll just have the frontier mod disabled, but if you have any advice/fix that would be greatly appreciated!! ^^
Hope y'all have a lovely day/night, wherever you are :)
- Acid, frontier fanatic!

p.s. if you need the full crash log(s) I can try and send them somewhere! literally brand new to github so I might struggle on here lol

**Comment by alejandrocoria** [comment]
Both JourneyMap and MapFrontiers use the Common Networking mod and include it inside each jar. MapFrontiers is on an older version but for some reason it tries to use the version included in JourneyMap instead of its own.

Until I release an updated version, you will have to roll back JourneyMap to beta 13.

**Comment by BatteryAc1dd** [comment]
Ah, alright! Ta.

**Comment by alejandrocoria** [comment]
This should no longer be an issue in the new version 1.21.1-2.7.0-beta.1.
