### ISSUE TITLE
"Groups" Section is inaccessible.

### ISSUE THREAD

**Issue by WhyDoINeedToQ** [alejandrocoria/MapFrontiers#67]
I'm not exactly sure what to include, so if any screenshots or other info is needed, I will be happy to include them. Despite the mod being on all client-sides and server sides, with myself being server owner, the F8 menu has Groups grayed out. Playing 1.20.1.

**Comment by alejandrocoria** [comment]
Did you close the issue because you found the solution? If so, can you tell me about it? There are other users who reported this problem in 1.20.1.

**Comment by WhyDoINeedToQ** [comment]
Yes, as it turns out I'm really not bright. Didn't realize you had to use a
command server-side to actually make oneself an operator, I thought that
role was automatically given to one who started a server
