### ISSUE TITLE
[Question] If MapFrontiers is installed on the server, do all clients *have* to also have MapFrontiers installed?

### ISSUE THREAD

**Issue by TheDogOfChaos** [alejandrocoria/MapFrontiers#69]
All there in the title.

**Comment by alejandrocoria** [comment]
It is not mandatory, but it is necessary for players who want to use the mod.

The mod on the server stores all the frontiers for all players and manages permissions.
The mod on the client renders the different screens, the HUD and interacts with the JourneyMap API to draw the frontiers on the maps and the right buttons on the fullscreen map.

If the mod is only on the server, the player will not see or be able to interact with the frontiers in any way.
If the mod is only in the client, the player can only create personal frontiers that only they will see.

**Comment by TheDogOfChaos** [comment]
Alright, thank you for the information!
