### ISSUE TITLE
AutoScaled Screen Crash 1.21.1(1.21.3)

### ISSUE THREAD

**Issue by SSilice** [alejandrocoria/MapFrontiers#70]
Hi I run this mod in a 1.21.3 modpack with no issues without the mod, once I try to use any of the buttons in Journeymap I get the following error 

java.lang.NoSuchMethodError: 'void games.alejandrocoria.mapfrontiers.client.gui.screen.AutoScaledScreen.method_57734(float)'

Not sure what is causing this. Tying crash log to this
[crash-2024-12-03_00.59.32-client.txt](https://github.com/user-attachments/files/17988694/crash-2024-12-03_00.59.32-client.txt)

**Comment by SSilice** [comment]
Actually to add just in general it seems to crash even with every other mod disabled and does not give that error. So more changing towards the question of is there any update on the 1.21.2/3 update?

**Comment by alejandrocoria** [comment]
The mod is currently only compatible with 1.21.1.
When I finish implementing the features planned for that version, I will release for versions 1.21.2 to 1.21.4.

**Comment by SSilice** [comment]
Sounds good! I look forward to it I quite enjoy the mod!

**Comment by alejandrocoria** [comment]
I've released new betas for 1.21.1 and 1.21.4.
I won't be releasing for 1.21.2 and 1.21.3.
