### ISSUE TITLE
Cant launch 2.7.0 beta2

### ISSUE THREAD

**Issue by Rozbiynk** [alejandrocoria/MapFrontiers#71]
Steps to reproduce:
install map frontiers with all dependies
try to launch
have crash
crash report: https://mclo.gs/HKXjuUV
list of mods:
![изображение](https://github.com/user-attachments/assets/8051c9fb-3b0b-4271-95f5-e51212b1f25d)

**Comment by alejandrocoria** [comment]
Fixed in the new beta 3.
Thanks for the report!
