### ISSUE TITLE
[Question] Modpack Support

### ISSUE THREAD

**Issue by Xarmat-GitHub** [alejandrocoria/MapFrontiers#9]
I am creating a modpack and need a way to inform the player about map zones.
Is it possible to auto generate zones with this mod? And how will I do this?

Example: 
Name: "Kingdom of Hellena", Region X: -5.000 | 5.000 Z: -5000 | 5000 color: red

When there is no way to do this, this can be an suggestion.

**Comment by alejandrocoria** [comment]
What you are asking is to inform players of manually created frontiers or to create frontiers automatically?
